### ISSUE TITLE
the Class Product have been declare in CM.DTO

### ISSUE THREAD

**Issue by datdatga113** [UtmoD/Cafeteria-Management-Software#43]
![image](https://user-images.githubusercontent.com/55282618/69841080-73772480-1290-11ea-9cfc-64118f15a557.png)
![image](https://user-images.githubusercontent.com/55282618/69841103-85f15e00-1290-11ea-89db-d2bd8f530c4d.png)
2 cái khác nhau, nhưng xài tên giống nhau

**Comment by UtmoD** [comment]
There must have been a mistake
